version: '2'
services:
  # kong
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_PASSWORD: "kong"
      KONG_CASSANDRA_CONTACT_POINTS: "kong-database"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    links:
      - kong-database
    ports:
      - "7000:8000"
      - "7443:8443"
#      - "7001:8001"
#      - "7444:8444"
      - "127.0.0.1:7001:8001"
      - "127.0.0.1:7444:8444"
    networks:
      - kong-network
  # kong database
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
      POSTGRES_PASSWORD: "kong"
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    networks:
      - kong-network
  phppgadmin_kong:
    image: dockage/phppgadmin
    ports:
      - "81:80"
    links:
     - kong-database
    environment:
      PHP_PG_ADMIN_SERVER_DESC: "PostgreSQL"
      PHP_PG_ADMIN_SERVER_HOST: "kong-database"
      PHP_PG_ADMIN_SERVER_PORT: "5432"
      PHP_PG_ADMIN_SERVER_DEFAULT_DB: "kong"
    networks:
      - kong-network

networks:
  kong-network:
    driver: bridge