version: '2'
services:
  #authentication services
  activiti-app:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: activiti-tomcat:06052020_1
    ports:
      - "8888:8080"
    depends_on:
      - activiti-mysql
    networks:
      - activiti-network
   
  # authentication database
  activiti-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "activiti"
      MYSQL_USER: "activiti"
      MYSQL_PASSWORD: "activiti"
      MYSQL_DATABASE: "activiti6ui"
    volumes:
      - ./db:/var/lib/mysql
    ports:
     - "0.0.0.0:3306:3306"
    networks:
      - activiti-network
 
networks:
  activiti-network:
    driver: bridge
