rootProject.name = "backend"
include(":api:authentication")
include(":data")
include(":data:data-workflow-cassandra")
include(":data:data-workflow-mongo")
include(":data:data-user-information")
include(":filesystem")
include(":notification")
include(":notification:notification-email")
include(":utilities")
include(":signature")
include(":workflow")
include(":workflow:workflow-manager")
include(":workflow:workflow-administration")
include(":portal-administration")

