rootProject.name = "backend"
include(":api:authentication")
include(":api:authorization")
include(":api:tenant")
include(":data")
include(":data:data-workflow-cassandra")
include(":data:data-workflow-mongo")
include(":data:data-user-information")
include(":data:data-user-authorization")
include(":data:data-tenant-information")
include(":filesystem")
include(":notification")
include(":notification:notification-email")
include(":utilities")
include(":utilities:util-model")
include(":utilities:util-authorization")
include(":signature")
include(":workflow")
include(":workflow:workflow-manager")
include(":workflow:workflow-administration")
include(":portal-administration")

