/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.itec.Administration;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Administration classUnderTest = new Administration();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
