version: '2'
services:
  #authentication services
  sedeelectronicagestor:
    build:
      context: ./
      dockerfile: Dockerfile
    image: sedeelectronica:23042020_1
    ports:
      - "6060:6060"
    networks:
      - authenticationnet
      - kong_kong-network
      - frontendnet


networks:
  frontendnet:
    driver: bridge
  autenticacion_authenticationnet:
    external: true
  kong_kong-network:
    external: true
