version: '2'
services:
  #authentication services
  sedeelectronicagestor:
    build:
      context: ./
      dockerfile: Dockerfile
    image: sedeelectronica:23042020_9
    ports:
      - "6060:5000"
    networks:
      - autenticacion_authenticationnet
      - kong_kong-network
      - frontendnetsedelectornica


networks:
  frontendnetsedelectornica:
    driver: bridge
  autenticacion_authenticationnet:
    external: true
  kong_kong-network:
    external: true
