version: '2'
services:
  #authentication services
  portaladministraciongestor:
    build:
      context: ./
      dockerfile: Dockerfile
    image: portaladministracion:06052020_1
    volumes:
      - ./config:/usr/src/app/src/config
    ports:
      - "7072:5000"
    networks:
      - frontendnetportaladministracion
      - kong_kong-network


networks:
  frontendnetportaladministracion:
    driver: bridge
  kong_kong-network:
    external: true